# Generated by Django 4.1.4 on 2023-01-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name="book",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="book",
            name="ref",
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book_manager.author",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="kind",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book_manager.kind",
            ),
        ),
    ]
