# Generated by Django 4.1.4 on 2023-01-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("name", "author")},
        ),
    ]
