# Generated by Django 4.1.4 on 2023-01-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book_manager", "0002_kind_rename_name_book_title_remove_book_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book_manager.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="kind",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book_manager.kind",
            ),
        ),
    ]
